spring.application.name=opsflow

spring.datasource.url=jdbc:postgresql://localhost:5432/opsflow
spring.datasource.username=postgres
spring.datasource.password=rohankanthale@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081